export const TRANSLATION_KEY = {
  // Step titles and descriptions
  "step1": {
    "title": "step1.title",
    "description": "step1.description"
  },
  "step2": {
    "title": "step2.title",
    "description": "step2.description"
  },
  "step3": {
    "title": "step3.title",
    "description": "step3.description"
  },
  
  // Section titles and descriptions
  "family_section": "family_section",
  "family_description": "family_description",
  "employment_section": "employment_section",
  "employment_description": "employment_description",
  "housing_section": "housing_section",
  "housing_description": "housing_description",
  "benefits_section": "benefits_section",
  "benefits_description": "benefits_description",
  "identity_section": "identity_section",
  "identity_description": "identity_description",
  "contact_section": "contact_section",
  "contact_description": "contact_description",
  "address_section": "address_section", 
  "address_description": "address_description",
  "consent_section": "consent_section",
  "notice_title": "notice_title",
  "notice_text": "notice_text",
  "financial_notice_title": "financial_notice_title",
  "financial_notice_text": "financial_notice_text",
  "final_notice_title": "final_notice_title",
  "final_notice_text": "final_notice_text",
  
  // Form field labels
  "fullName": "fullName",
  "fullName_placeholder": "fullName_placeholder",
  "fullName_help": "fullName_help",
  "nationalId": "nationalId",
  "nationalId_placeholder": "nationalId_placeholder",
  "nationalId_help": "nationalId_help",
  "dateOfBirth": "dateOfBirth",
  "dateOfBirth_help": "dateOfBirth_help",
  "gender": "gender",
  "gender_help": "gender_help",
  "gender_select": "gender_select",
  "gender_options": {
    "male": "gender_options.male",
    "female": "gender_options.female",
    "other": "gender_options.other",
    "prefer_not_to_say": "gender_options.prefer_not_to_say"
  },
  "email": "email",
  "email_placeholder": "email_placeholder",
  "email_help": "email_help",
  "phone": "phone",
  "phone_placeholder": "phone_placeholder",
  "phone_help": "phone_help",
  "address": "address",
  "address_placeholder": "address_placeholder",
  "address_help": "address_help",
  "city": "city",
  "city_placeholder": "city_placeholder",
  "city_help": "city_help",
  "state": "state",
  "state_placeholder": "state_placeholder",
  "state_help": "state_help",
  "country": "country",
  "country_help": "country_help",
  "country_select": "country_select",
  "postalCode": "postalCode",
  "postalCode_placeholder": "postalCode_placeholder",
  "postalCode_help": "postalCode_help",
  "maritalStatus": "maritalStatus",
  "maritalStatus_help": "maritalStatus_help",
  "maritalStatus_select": "maritalStatus_select",
  "maritalStatus_options": {
    "single": "maritalStatus_options.single",
    "married": "maritalStatus_options.married",
    "divorced": "maritalStatus_options.divorced",
    "widowed": "maritalStatus_options.widowed",
    "separated": "maritalStatus_options.separated"
  },
  "numberOfDependents": "numberOfDependents",
  "numberOfDependents_help": "numberOfDependents_help",
  "employmentStatus": "employmentStatus",
  "employmentStatus_help": "employmentStatus_help",
  "employmentStatus_select": "employmentStatus_select",
  "employmentStatus_options": {
    "employed": "employmentStatus_options.employed",
    "employed_full_time": "employmentStatus_options.employed_full_time",
    "employed_part_time": "employmentStatus_options.employed_part_time",
    "part_time": "employmentStatus_options.part_time",
    "self_employed": "employmentStatus_options.self_employed",
    "unemployed": "employmentStatus_options.unemployed",
    "retired": "employmentStatus_options.retired",
    "student": "employmentStatus_options.student",
    "disabled": "employmentStatus_options.disabled"
  },
  "occupation": "occupation",
  "occupation_placeholder": "occupation_placeholder",
  "occupation_help": "occupation_help",
  "employer": "employer",
  "employer_placeholder": "employer_placeholder",
  "employer_help": "employer_help",
  "monthlyIncome": "monthlyIncome",
  "monthlyIncome_help": "monthlyIncome_help",
  "monthlyExpenses": "monthlyExpenses",
  "monthlyExpenses_help": "monthlyExpenses_help",
  "totalSavings": "totalSavings",
  "totalSavings_help": "totalSavings_help",
  "totalDebt": "totalDebt",
  "totalDebt_help": "totalDebt_help",
  "housingStatus": "housingStatus",
  "housingStatus_help": "housingStatus_help",
  "housingStatus_select": "housingStatus_select",
  "housingStatus_options": {
    "own": "housingStatus_options.own",
    "rent": "housingStatus_options.rent",
    "living_with_family": "housingStatus_options.living_with_family",
    "homeless": "housingStatus_options.homeless",
    "other": "housingStatus_options.other"
  },
  "monthlyRent": "monthlyRent",
  "monthlyRent_help": "monthlyRent_help",
  "receivingBenefits": "receivingBenefits",
  "receivingBenefits_help": "receivingBenefits_help",
  "receivingBenefits_select": "receivingBenefits_select",
  "benefitTypes": "benefitTypes",
  "benefitTypes_help": "benefitTypes_help",
  "benefitTypes_options": {
    "unemployment": "benefitTypes_options.unemployment",
    "disability": "benefitTypes_options.disability",
    "housing": "benefitTypes_options.housing",
    "food": "benefitTypes_options.food",
    "medical": "benefitTypes_options.medical",
    "elderly": "benefitTypes_options.elderly",
    "family": "benefitTypes_options.family",
    "other": "benefitTypes_options.other"
  },
  "previouslyApplied": "previouslyApplied",
  "previouslyApplied_help": "previouslyApplied_help",
  "previouslyApplied_select": "previouslyApplied_select",
  "financialSituation": "financialSituation",
  "financialSituation_placeholder": "financialSituation_placeholder",
  "financialSituation_help": "financialSituation_help",
  "employmentCircumstances": "employmentCircumstances",
  "employmentCircumstances_placeholder": "employmentCircumstances_placeholder",
  "employmentCircumstances_help": "employmentCircumstances_help",
  "reasonForApplying": "reasonForApplying",
  "reasonForApplying_placeholder": "reasonForApplying_placeholder",
  "reasonForApplying_help": "reasonForApplying_help",
  "additionalComments": "additionalComments",
  "additionalComments_placeholder": "additionalComments_placeholder",
  "additionalComments_help": "additionalComments_help",
  "agreeToTerms": "agreeToTerms",
  "agreeToTerms_help": "agreeToTerms_help",
  "consentToDataProcessing": "consentToDataProcessing",
  "consentToDataProcessing_help": "consentToDataProcessing_help",
  "allowContactForClarification": "allowContactForClarification",
  "allowContactForClarification_help": "allowContactForClarification_help",
  
  // Status messages
  "auto_saved": "auto_saved",
  "submission_success": "submission_success",
  "submission_success_message": "submission_success_message",
  "start_new_application": "start_new_application",
  "processing_time": "processing_time",
  "next_steps": "next_steps",
  "next_steps_items": {
    "review_application": "next_steps_items.review_application",
    "email_updates": "next_steps_items.email_updates",
    "keep_application_id": "next_steps_items.keep_application_id"
  },
  "application_reference_note": "application_reference_note",
  "application_id": "application_id",
  "confirmation_email_sent": "confirmation_email_sent",
  
  // Common actions (with namespace prefix)
  "common": {
    "actions": {
      "close": "common:actions.close",
      "copy": "common:actions.copy",
      "copied": "common:actions.copied"
    },
    "submitted_at": "common:submitted_at"
  }
} as const;
